# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
#              "you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#      "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]
question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean", "difficulty": "medium",
     "question": "Nintendo started out as a playing card manufacturer.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The Ace Attorney trilogy was supposed to end with 'Phoenix Wright: Ace Attorney - Trials and "
                 "Tribulations' as its final game.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean", "difficulty": "medium",
     "question": "In Riot Games 'League of Legends'; the name of Halloween event is called 'The Reckoning'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The Fiat Multipla is a drivable car in 'Forza Horizon 3'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "In 'League of Legends', there exists four different types of Dragon.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Hidden in the files for 'Mario Kart Arcade' is a picture of the Beslan school hostage crisis.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "During pre-production of 'Super Mario Bros.', Mario originally was meant to shoot bullets.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The game Garry's Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Minecraft wasn't the original name to Minecraft.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]}
]


